/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Urban(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  return (
    <group {...props} dispose={null}>
        <group position={[0, -0.2, -0.17]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[1.59, -1.26, 0]} rotation={[0, 0, -Math.PI]}>
            <group position={[0, 0.05, 0]}>
              <mesh geometry={nodes['Component#50'].geometry} material={materials['*5']} position={[0.06, 0.06, 2.2]} rotation={[0, 0, Math.PI / 2]} scale={[0.1, 0.1, 6.03]} />
              <mesh geometry={nodes.model.geometry} material={materials['*5']} position={[0.11, 0, 0.25]} rotation={[0, 0, Math.PI / 2]}>
                <mesh geometry={nodes['Component#18'].geometry} material={materials['*5']} position={[0.14, 0.02, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_1'].geometry} material={materials['*5']} position={[0.14, 0.1, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_2'].geometry} material={materials['*5']} position={[-0.03, 0.1, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_3'].geometry} material={materials['*5']} position={[-0.03, 0.02, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_4'].geometry} material={materials['*5']} position={[0.11, 0.02, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_5'].geometry} material={materials['*5']} position={[0.11, 0.1, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_2_1'].geometry} material={materials['*5']} position={[-0.01, 0.02, 0.01]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_3_1'].geometry} material={materials['*5']} position={[-0.01, 0.1, 0.01]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes.model_2.geometry} material={materials['*5']} position={[0.11, 0.02, -0.05]} scale={[1.07, 1.13, 1.13]} />
              </mesh>
            </group>
            <group position={[3.05, 0.05, 0]}>
              <mesh geometry={nodes['Component#50_2'].geometry} material={materials['*5']} position={[0.06, 0.06, 2.2]} rotation={[0, 0, Math.PI / 2]} scale={[0.1, 0.1, 6.03]} />
              <mesh geometry={nodes.model_3.geometry} material={materials['*5']} position={[0.11, 0, 0.25]} rotation={[0, 0, Math.PI / 2]}>
                <mesh geometry={nodes['Component#18_6'].geometry} material={materials['*5']} position={[0.14, 0.02, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_7'].geometry} material={materials['*5']} position={[0.14, 0.1, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_8'].geometry} material={materials['*5']} position={[-0.03, 0.1, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_9'].geometry} material={materials['*5']} position={[-0.03, 0.02, -0.04]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
                <mesh geometry={nodes['Component#18_10'].geometry} material={materials['*5']} position={[0.11, 0.02, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_11'].geometry} material={materials['*5']} position={[0.11, 0.1, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_4_1'].geometry} material={materials['*5']} position={[-0.01, 0.02, 0.01]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes['Component#18_5_1'].geometry} material={materials['*5']} position={[-0.01, 0.1, 0.01]} rotation={[0, 0, Math.PI / 2]} scale={[1, 0.8, 1]} />
                <mesh geometry={nodes.model_4.geometry} material={materials['*5']} position={[0.11, 0.02, -0.05]} scale={[1.07, 1.13, 1.13]} />
              </mesh>
            </group>
            <group position={[0.01, 0, 2.17]}>
              <group position={[0, 0.16, 0.05]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.06, 0.06]}>
                <group position={[0, -0.08, -0.03]} scale={[40.37, 20.18, 20.18]}>
                  <mesh geometry={nodes.model_5.geometry} material={materials['*52']} position={[0, 0, 0.01]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.17, 0.17, 0.03]} />
                  <mesh geometry={nodes.model_6.geometry} material={materials['*52']} position={[0, 0, 0]} scale={[0.03, 0.06, 0.06]} />
                </group>
              </group>
              <mesh geometry={nodes.model_7.geometry} material={materials['*5']} position={[0, 0, 0.01]}>
                <mesh geometry={nodes['Component#94'].geometry} material={materials['*5']} position={[0, 0.04, 0.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_1'].geometry} material={materials['*5']} position={[0, 0.06, 0.09]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_2'].geometry} material={materials['*5']} position={[0, 0.2, 0.13]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_3'].geometry} material={materials['*5']} position={[0, 0.17, 0.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_4'].geometry} material={materials['*5']} position={[0, 0.18, 0.09]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </group>
            <group position={[3.16, 0, 2.17]}>
              <group position={[0, 0.09, 0.05]} scale={[0.03, 0.06, 0.06]}>
                <group position={[0, -0.08, -0.03]} scale={[40.37, 20.18, 20.18]}>
                  <mesh geometry={nodes.model_8.geometry} material={materials['*52']} position={[0, 0, 0.01]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.17, 0.17, 0.03]} />
                  <mesh geometry={nodes.model_9.geometry} material={materials['*52']} position={[0, 0, 0]} scale={[0.03, 0.06, 0.06]} />
                </group>
              </group>
              <mesh geometry={nodes.model_10.geometry} material={materials['*5']} position={[0, 0, 0.01]}>
                <mesh geometry={nodes['Component#94_5'].geometry} material={materials['*5']} position={[0, 0.04, 0.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_6'].geometry} material={materials['*5']} position={[0, 0.06, 0.09]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_7'].geometry} material={materials['*5']} position={[0, 0.2, 0.13]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_8'].geometry} material={materials['*5']} position={[0, 0.17, 0.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
                <mesh geometry={nodes['Component#94_9'].geometry} material={materials['*5']} position={[0, 0.18, 0.09]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </group>
            <mesh geometry={nodes.model_11.geometry} material={materials['*5']} position={[0, 0.01, 2.18]} scale={[1.05, 1, 1]} />
          </group>
          <group position={[4.73, -1.39, 2.15]} rotation={[0, 0, -Math.PI]}>
            <group position={[6.3, -2.54, 0.5]}>
              <mesh geometry={nodes['Component#46'].geometry} material={materials['*5']} position={[0, 0.02, 0.14]} rotation={[1.57, 1.57, 0]} />
              <mesh geometry={nodes['Component#46_1'].geometry} material={materials['*5']} position={[0, 0.03, 0.1]} rotation={[1.57, 1.57, 0]} />
              <mesh geometry={nodes['Component#46_2'].geometry} material={materials['*5']} position={[0, 0.03, 0.04]} rotation={[1.57, 1.57, 0]} />
              <mesh geometry={nodes['Component#46_3'].geometry} material={materials['*5']} position={[0, 0.03, 0.01]} rotation={[1.57, 1.57, 0]} />
              <mesh geometry={nodes['Component#46_4'].geometry} material={materials['*5']} position={[0, 0.07, 0.09]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.model_12.geometry} material={materials['*5']} position={[0, 0.01, 0]} />
            </group>
            <group position={[3.15, -2.54, 0.5]} rotation={[0.01, 0, 0]}>
              <mesh geometry={nodes['Component#46_5'].geometry} material={materials['*5']} position={[0, 0.02, 0.14]} rotation={[1.57, -1.57, 0]} />
              <mesh geometry={nodes['Component#46_6'].geometry} material={materials['*5']} position={[0, 0.03, 0.1]} rotation={[1.57, -1.57, 0]} />
              <mesh geometry={nodes['Component#46_7'].geometry} material={materials['*5']} position={[0, 0.03, 0.04]} rotation={[1.57, -1.57, 0]} />
              <mesh geometry={nodes['Component#46_8'].geometry} material={materials['*5']} position={[0, 0.03, 0.01]} rotation={[1.57, -1.57, 0]} />
              <mesh geometry={nodes['Component#46_9'].geometry} material={materials['*5']} position={[0, 0.07, 0.09]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
              <mesh geometry={nodes.model_13.geometry} material={materials['*5']} position={[0, 0.01, 0]} />
            </group>
            <mesh geometry={nodes.model_14.geometry} material={materials['*5']} position={[3.15, -2.53, 0.5]} scale={[1.05, 1, 1]} />
          </group>
          <group position={[4.61, 1.13, 2.14]} rotation={[0, 0, -Math.PI]}>
            <group position={[6.18, 2.94, 0]} rotation={[-0.19, 0, Math.PI / 2]}>
              <group position={[-2.97, 0, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 10.44, 1]}>
                <group position={[0.03, 0, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['Component#49_5'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['Component#49_6'].geometry} material={materials['<auto>']} />
                </group>
                <group position={[0.03, 0.24, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['560-1101#1_1'].geometry} material={materials['*1']} />
                  <mesh geometry={nodes['560-1101#1_6'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['560-1101#1_7'].geometry} material={materials['*24']} />
                </group>
                <group position={[0.03, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['550-6101_1'].geometry} material={materials['<auto>']} />
                  <mesh geometry={nodes['550-6101_6'].geometry} material={materials['*5']} />
                </group>
                <group position={[0.04, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_7'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.04, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_6'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_7'].geometry} material={materials['*1']} />
                </group>
                <mesh geometry={nodes.model_15.geometry} material={materials['*5']} position={[0, 0, 0.1]} scale={[1, 0.08, 1.07]} />
              </group>
              <mesh geometry={nodes.model_16.geometry} material={materials['*5']} position={[-0.55, 0, -0.03]} scale={[1, 1.09, 1]} />
            </group>
            <group position={[5.41, 2.94, 0]} rotation={[-0.19, 0, Math.PI / 2]}>
              <group position={[-2.97, 0, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 10.44, 1]}>
                <group position={[0.03, 0, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['Component#49_5'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['Component#49_6'].geometry} material={materials['<auto>']} />
                </group>
                <group position={[0.04, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_6'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_7'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.03, 0.24, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['560-1101#1_2_1'].geometry} material={materials['*1']} />
                  <mesh geometry={nodes['560-1101#1_2_2'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['560-1101#1_2_3'].geometry} material={materials['*24']} />
                </group>
                <group position={[0.03, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['550-6101_2_1'].geometry} material={materials['<auto>']} />
                  <mesh geometry={nodes['550-6101_2_2'].geometry} material={materials['*5']} />
                </group>
                <group position={[0.04, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_2_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_2_2'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_3_3'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_3_4'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_2_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_2_2'].geometry} material={materials['*1']} />
                </group>
              </group>
              <mesh geometry={nodes.model_17.geometry} material={materials['*5']} position={[-0.55, 0, -0.03]} scale={[1, 1.09, 1]} />
            </group>
            <group position={[4.63, 2.94, 0]} rotation={[-0.19, 0, Math.PI / 2]}>
              <group position={[-2.97, 0, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 10.44, 1]}>
                <group position={[0.03, 0, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['Component#49_5'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['Component#49_6'].geometry} material={materials['<auto>']} />
                </group>
                <group position={[0.04, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_6'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_7'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_3_3'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_3_4'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.03, 0.24, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['560-1101#1_3_1'].geometry} material={materials['*1']} />
                  <mesh geometry={nodes['560-1101#1_3_2'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['560-1101#1_3_3'].geometry} material={materials['*24']} />
                </group>
                <group position={[0.03, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['550-6101_3_1'].geometry} material={materials['<auto>']} />
                  <mesh geometry={nodes['550-6101_3_2'].geometry} material={materials['*5']} />
                </group>
                <group position={[0.04, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_4_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_4_2'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_3_2'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_3_3'].geometry} material={materials['*1']} />
                </group>
              </group>
              <mesh geometry={nodes.model_18.geometry} material={materials['*5']} position={[-0.55, 0, -0.03]} scale={[1, 1.09, 1]} />
            </group>
            <group position={[3.86, 2.94, 0]} rotation={[-0.19, 0, Math.PI / 2]}>
              <group position={[-2.97, 0, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 10.44, 1]}>
                <group position={[0.03, 0, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['Component#49_5'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['Component#49_6'].geometry} material={materials['<auto>']} />
                </group>
                <group position={[0.04, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_6'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_7'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_3_3'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_3_4'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.03, 0.24, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['560-1101#1_4_1'].geometry} material={materials['*1']} />
                  <mesh geometry={nodes['560-1101#1_4_2'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['560-1101#1_4_3'].geometry} material={materials['*24']} />
                </group>
                <group position={[0.03, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['550-6101_4_1'].geometry} material={materials['<auto>']} />
                  <mesh geometry={nodes['550-6101_4_2'].geometry} material={materials['*5']} />
                </group>
                <group position={[0.04, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_5_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_5_2'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.01, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_4_2'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_4_3'].geometry} material={materials['*1']} />
                </group>
              </group>
              <mesh geometry={nodes.model_19.geometry} material={materials['*5']} position={[-0.55, 0, -0.03]} scale={[1, 1.09, 1]} />
            </group>
            <group position={[3.03, 2.94, 0]} rotation={[-0.19, 0, -Math.PI / 2]}>
              {/* <group position={[0.48, 0, -0.04]}>
                <group position={[1.56, 0, 0]} scale={[1.25, 1.25, 1.98]}>
                  <mesh geometry={nodes['Component#52_10'].geometry} material={materials['*31']} />
                  <mesh geometry={nodes['Component#52_11'].geometry} material={materials['*32']} />
                </group>
                <group position={[0.32, 0, 0]} scale={[1.25, 1.25, 1.98]}>
                  <mesh geometry={nodes['Component#52_10'].geometry} material={materials['*31']} />
                  <mesh geometry={nodes['Component#52_11'].geometry} material={materials['*32']} />
                </group>
              </group> */}
              <group position={[2.97, 0, -0.03]} rotation={[0, 0, Math.PI / 2]} scale={[1, 10.44, 1]}>
                <group position={[0.08, 0, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['Component#49_5'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['Component#49_6'].geometry} material={materials['<auto>']} />
                </group>
                <group position={[0.09, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 1.37]}>
                  <mesh geometry={nodes['3202127_6'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202127_7'].geometry} material={materials['*1']} />
                </group>
                <group position={[0.03, 0.24, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['560-1101#1_5_1'].geometry} material={materials['*1']} />
                  <mesh geometry={nodes['560-1101#1_5_2'].geometry} material={materials['*5']} />
                  <mesh geometry={nodes['560-1101#1_5_3'].geometry} material={materials['*24']} />
                </group>
                <group position={[0.03, 0, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.1, 6]}>
                  <mesh geometry={nodes['550-6101_5_1'].geometry} material={materials['<auto>']} />
                  <mesh geometry={nodes['550-6101_5_2'].geometry} material={materials['*5']} />
                </group>
                <group position={[0.04, 0, 0.1]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.1, 0.1, 2]}>
                  <mesh geometry={nodes['3202130#1_6_1'].geometry} material={materials['*24']} />
                  <mesh geometry={nodes['3202130#1_6_2'].geometry} material={materials['*1']} />
                </group>
                <mesh geometry={nodes.model_20.geometry} material={materials['*5']} position={[0, 0, 0.1]} scale={[1, 0.08, 1.07]} />
              </group>
              <mesh geometry={nodes.model_21.geometry} material={materials['*5']} position={[0.55, 0, -0.03]} scale={[1, 1.09, 1]} />
            </group>
            <group position={[1.05, 2.42, 0.17]} rotation={[-0.19, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.model_22_1.geometry} material={materials['*8']} />
              <mesh geometry={nodes.model_22_2.geometry} material={materials['*25']} />
            </group>
            <group position={[1.82, 2.42, 0.17]} rotation={[-0.19, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.model_23_1.geometry} material={materials['*8']} />
              <mesh geometry={nodes.model_23_2.geometry} material={materials['*25']} />
            </group>
            <group position={[2.6, 2.42, 0.17]} rotation={[-0.19, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.model_24_1.geometry} material={materials['*8']} />
              <mesh geometry={nodes.model_24_2.geometry} material={materials['*25']} />
            </group>
            <group position={[3.37, 2.42, 0.17]} rotation={[-0.19, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.model_25_1.geometry} material={materials['*8']} />
              <mesh geometry={nodes.model_25_2.geometry} material={materials['*25']} />
            </group>
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('models/urban.glb')
