/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import AppContext from "../../context/AppContext";
import { useSnapshot } from "valtio"
import state from "../../state"
import {lengths} from '../../utils/constant';


export function Frame(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  const list = [];
  const frame_cnt = parseInt(props.length / props.frame_int_size);
  const frame_size = props.length / frame_cnt - 0.2;

  const px = 110.85;
  const py = 0;
  const pz = 0;
  const rx = 0.19;
  const ry = 0;
  const rz = Math.PI / 2;
  const sc = frame_size / props.frame_int_size;
  const dx = px * (sc - 1.0);

  for (var i = 0 ; i < frame_cnt ; i++ ) {
    list.push(
      <group
        scale={[1, frame_size / props.frame_int_size, 1]}
        position = {[px + dx + i * frame_size, py + props.dy, pz + props.dz]}
        rotation={[rx, ry, rz]}
      >
          <mesh castShadow receiveShadow geometry={nodes.mesh_11.geometry} material={materials.material_8} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_12.geometry} material={materials.material_25} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_13.geometry} material={materials.material_25} />
      </group>
    )
  }

  return(
    <group>
      <group position={[0, 7.11, 83.19]}>
        {list}
      </group>
    </group>
  );
}

export function BackSide(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  const {dx, dy, dz} = props;
  return (
    <group scale={[props.sx, 1, 1]} position={[dx, dy, dz]}>
      <group position={[124.19, 102.29, 96.34]} rotation={[0, 0, -Math.PI]} scale={[1.05, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_82.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_83.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_84.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_85.geometry} material={materials.material_5} />
      </group>
    </group>
  )
}

export function FrontSide(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  const {dx, dy, dz} = props;
  return (
    <group scale={[props.sx, 1, 1]} position = {[dx, dy, dz]}>
      <group position={[124.35, 7.71, 77.91]} rotation={[0, 0, -Math.PI]} scale={[1.05, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_2.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_3.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_4.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_5.geometry} material={materials.material_5} />
        <lineSegments geometry={nodes.mesh_6.geometry} material={materials.edge_color898989255} />
        <lineSegments geometry={nodes.mesh_7.geometry} material={materials.edge_color898989255} />
      </group>
    </group>
  )
}

export function Bar(props) {
  const { nodes, materials } = useGLTF('models/urban.glb');
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.mesh_279_instance_0.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_280_instance_0.geometry} material={materials.material_5} />
    </group>
  )
}
export function Bars(props) {
  const {dx, sz} = props;
  const list = [];
  list.push(
    <Bar position={[122.38 + dx, 3.94, 78.72]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.1, 0.1, 6.03]} />
  );
  list.push(
    <Bar position={[2.09, 3.94, 78.72]} rotation={[0, 0, -Math.PI / 2]} scale={[-0.1, 0.1, 6.03]} />
  );

  return (
    <group scale={[1, 1, sz]}>
      {list}
    </group>
  )
}

export function Bottom(props) {
  const { nodes, materials} = useGLTF('models/urban.glb');
  return (
    <group {...props}>
      <group position={[4.48, 0.97, -1.85]} scale={[1.07, 1.13, 1.13]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_68.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_69.geometry} material={materials.material_5} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.instance_10.geometry} material={materials.material_5} position={[5.41, 0.78, -1.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_11.geometry} material={materials.material_5} position={[5.41, 4.05, -1.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_12.geometry} material={materials.material_5} position={[-1.01, 4.05, -1.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_13.geometry} material={materials.material_5} position={[-1.01, 0.78, -1.69]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.49, 1, 1.49]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_16.geometry} material={materials.material_5} position={[4.48, 0.85, 0.28]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_17.geometry} material={materials.material_5} position={[4.48, 3.81, 0.28]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.8, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_14.geometry} material={materials.material_5} position={[-0.48, 0.85, 0.28]} rotation={[0, 0, Math.PI / 2]} scale={[-1, 0.8, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.instance_15.geometry} material={materials.material_5} position={[-0.48, 3.81, 0.28]} rotation={[0, 0, Math.PI / 2]} scale={[-1, 0.8, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_70.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_71.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_72.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_73.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_74.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_75.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_76.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_77.geometry} material={materials.material_5} />
      <mesh castShadow receiveShadow geometry={nodes.mesh_78.geometry} material={materials.material_5} />
      <lineSegments geometry={nodes.mesh_79.geometry} material={materials.edge_color898989255} />
      <lineSegments geometry={nodes.mesh_80.geometry} material={materials.edge_color898989255} />
      <lineSegments geometry={nodes.mesh_81.geometry} material={materials.edge_color898989255} />
    </group>
  )
}

export function Bottoms(props) {
  const list = [];
  const px = -0.09;
  const py = 5.93;
  const pz = 2.01;
  list.push(
    <Bottom position={[px, py, pz]} rotation={[0, 0, -Math.PI / 2]} />
  )
  list.push(
    <Bottom position={[px + 120.3 + props.dx, py, pz]} rotation={[0, 0, -Math.PI / 2]} />
  );
  return (
    <group>
      {list}
    </group>
  );
}

export function LeftSide(props) {
  const { nodes, materials} = useGLTF('models/urban.glb');
  const sy = props.sy;
  // const dy = 100.91 * (1 - sy);
  return (
    <group position={[0, 0, props.dz]}>
        <group position={[0.11, 100.91, 100.67]} rotation={[0.19, 0, Math.PI]} scale={[-1, 0.83, 1.07]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_28.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_29.geometry} material={materials.material_5} />
        </group>
        <group position={[1.16, 100.75, 101.51]} rotation={[-1.38, 0, -Math.PI]} scale={[-0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_98_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_99.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_99_1.geometry} material={materials.material_1} />
        </group>
        <group position={[1.16, 100.77, 101.4]} rotation={[-1.38, 0, -Math.PI]} scale={[0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_100.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_102.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_102_1.geometry} material={materials.material_1} />
        </group>
        <group position={[1.82, 100.9, 100.75]} rotation={[-1.38, 0, 0]} scale={[0.1, 0.1, 20.88]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_182_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_183.geometry} material={materials.material_1} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_183_1.geometry} material={materials.material_24} />
        </group>
        <group position={[1.19, 3.8, 80.68]} rotation={[-1.38, 0, -Math.PI]} scale={[0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_184.geometry} material={materials.material_1} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_184_1.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_185_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_186.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_186_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_187.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_187_1.geometry} material={materials.__auto_} />
        </group>
    </group>
  )
}

export function RightSide(props) {
  const { nodes, materials} = useGLTF('models/urban.glb');
  const {dx, dy, dz} = props;
  return (
    <group position = {[dx, dy, dz]}>
      <group position={[124.35, 100.91, 100.67]} rotation={[0.19, 0, -Math.PI]} scale={[1, 0.83, 1.07]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_50.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_51.geometry} material={materials.material_5} />
      </group>
      <group position={[123.3, 100.75, 101.51]} rotation={[-1.38, 0, Math.PI]} scale={[0.1, 0.1, 62.63]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_270.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_271.geometry} material={materials.__auto_} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_271_1.geometry} material={materials.material_1} />
      </group>
      <group position={[122.64, 100.9, 100.75]} rotation={[-1.38, 0, 0]} scale={[-0.1, 0.1, 20.88]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_189_instance_3.geometry} material={materials.material_24} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_190.geometry} material={materials.material_1} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_190_1.geometry} material={materials.material_24} />
      </group>
      <group position={[123.27, 3.8, 80.68]} rotation={[-1.38, 0, Math.PI]} scale={[-0.1, 0.1, 62.63]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_272.geometry} material={materials.material_1} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_272_1.geometry} material={materials.__auto_} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_273.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_274.geometry} material={materials.material_24} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_274_1.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_275.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_275_1.geometry} material={materials.__auto_} />
      </group>
      <group position={[123.3, 100.77, 101.4]} rotation={[-1.38, 0, Math.PI]} scale={[-0.1, 0.1, 62.63]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_276.geometry} material={materials.__auto_} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_276_1.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_277.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_278.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_278_1.geometry} material={materials.material_1} />
      </group>
    </group>
  )
}

export function Stick(props) {
  const { nodes, materials} = useGLTF('models/urban.glb');
  return (
    <group {...props}>
        <group position={[31.71, 3.8, 80.68]} rotation={[-1.38, 0, -Math.PI]} scale={[0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_184.geometry} material={materials.material_1} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_184_1.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_185_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_186.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_186_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_187.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_187_1.geometry} material={materials.__auto_} />
        </group>
        <group position={[31.68, 100.77, 101.4]} rotation={[-1.38, 0, -Math.PI]} scale={[0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_100.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_102.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_102_1.geometry} material={materials.material_1} />
        </group>
        <group position={[31.09, 100.9, 100.75]} rotation={[-1.38, 0, 0]} scale={[-0.1, 0.1, 20.88]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_189_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_190.geometry} material={materials.material_1} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_190_1.geometry} material={materials.material_24} />
        </group>
        <group position={[32.34, 100.9, 100.75]} rotation={[-1.38, 0, 0]} scale={[0.1, 0.1, 20.88]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_182_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_183.geometry} material={materials.material_1} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_183_1.geometry} material={materials.material_24} />
        </group>
        <group position={[31, 100.81, 101.23]} rotation={[-1.38, 0, -Math.PI]} scale={[0.1, 0.1, 14.26]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_191.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_191_1.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_192_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_193_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_194_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_195_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_196_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_197_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_198_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_199_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_200_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_201_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_202_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_203_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_204_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_205_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_206_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_207_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_208_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_209_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_210_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_211_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_212_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_213_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_214_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_215_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_216_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_217_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_218_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_219_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_220_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_221_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_222_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_223_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_224_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_225_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_226_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_227_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_228_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_229_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_230_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_231_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_232_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_233_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_234_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_235_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_236_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_237_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_238_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_239_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_240_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_241_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_242_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_243_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_244_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_245_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_246_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_247_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_248_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_249_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_250_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_251_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_252_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_253_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_254_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_255_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_256_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_257_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_258_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_259_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_260_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_261_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_262_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_263_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_264_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_265_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_266_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_267_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_268_instance_0.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_269_instance_0.geometry} material={materials.material_1} />
        </group>
        <group position={[32.36, 100.81, 101.23]} rotation={[-1.38, 0, -Math.PI]} scale={[-0.1, 0.1, 14.26]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_103.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_103_1.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_104_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_105_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_106_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_107_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_108_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_109_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_110_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_111_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_112_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_113_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_114_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_115_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_116_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_117_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_118_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_119_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_120_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_121_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_122_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_123_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_124_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_125_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_126_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_127_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_128_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_129_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_130_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_131_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_132_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_133_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_134_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_135_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_136_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_137_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_138_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_139_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_140_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_141_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_142_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_143_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_144_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_145_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_146_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_147_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_148_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_149_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_150_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_151_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_152_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_153_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_154_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_155_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_156_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_157_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_158_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_159_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_160_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_161_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_162_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_163_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_164_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_165_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_166_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_167_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_168_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_169_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_170_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_171_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_172_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_173_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_174_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_175_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_176_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_177_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_178_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_179_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_180_instance_1.geometry} material={materials.material_24} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_181_instance_1.geometry} material={materials.material_1} />
        </group>
        <group position={[31.68, 100.75, 101.51]} rotation={[-1.38, 0, -Math.PI]} scale={[-0.1, 0.1, 62.63]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_98_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_99.geometry} material={materials.__auto_} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_99_1.geometry} material={materials.material_1} />
        </group>
    </group>
  )
}

export function CornerFR(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  return (
    <group {...props}>
      <group position={[124.27, 8.1, 77.87]} rotation={[0, 0, Math.PI]} scale={[-1, 1, 1]}>
        <group position={[0.2, 1.75, 1.51]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_88_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_89_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_90_instance_0.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 2.51, 3.42]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_88_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_89_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_90_instance_1.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 7.85, 5.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_88_instance_2.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_89_instance_2.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_90_instance_2.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 6.73, 1.51]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_88_instance_3.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_89_instance_3.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_90_instance_3.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 7.15, 3.43]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_88_instance_4.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_89_instance_4.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_90_instance_4.geometry} material={materials.material_5} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.mesh_91.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_92.geometry} material={materials.material_5} />
      </group>
      <group position={[124.47, 1.98, 79.47]} scale={[0.03, 0.06, 0.06]}>
        <group position={[0, -3.03, -1.21]} scale={[40.37, 20.18, 20.18]}>
          <group position={[0, 0, 0.53]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.17, 0.17, 0.03]}>
            <mesh castShadow receiveShadow geometry={nodes.mesh_283_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_284_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_285_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_286_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_287_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_288_instance_0.geometry} material={materials.material_52} />
          </group>
          <group position={[0, -0.16, -0.19]} scale={[0.03, 0.06, 0.06]}>
            <mesh castShadow receiveShadow geometry={nodes.mesh_289_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_290_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_291_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_292_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_293_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_294_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_295_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_296_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_297_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_298_instance_0.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_299_instance_0.geometry} material={materials.material_52} />
            <lineSegments geometry={nodes.mesh_300_instance_0.geometry} material={materials.edge_color153153153255} />
          </group>
        </group>
      </group>
    </group>
  )
}

export function CornerFL(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  return (
    <group {...props}>
      <group position={[0.2, 8.1, 77.87]} rotation={[0, 0, -Math.PI]}>
        <group position={[0.2, 1.75, 1.51]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_93_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_94_instance_0.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_95_instance_0.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 2.51, 3.42]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_93_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_94_instance_1.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_95_instance_1.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 7.85, 5.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_93_instance_2.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_94_instance_2.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_95_instance_2.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 6.73, 1.51]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_93_instance_3.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_94_instance_3.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_95_instance_3.geometry} material={materials.material_5} />
        </group>
        <group position={[0.2, 7.15, 3.43]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_93_instance_4.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_94_instance_4.geometry} material={materials.material_5} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_95_instance_4.geometry} material={materials.material_5} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.mesh_96.geometry} material={materials.material_5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_97.geometry} material={materials.material_5} />
      </group>
      <group position={[0, 4.43, 79.47]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.06, 0.06]}>
        <group position={[0, -3.03, -1.21]} scale={[40.37, 20.18, 20.18]}>
          <group position={[0, 0, 0.53]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.17, 0.17, 0.03]}>
            <mesh castShadow receiveShadow geometry={nodes.mesh_283_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_284_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_285_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_286_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_287_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_288_instance_1.geometry} material={materials.material_52} />
          </group>
          <group position={[0, -0.16, -0.19]} scale={[0.03, 0.06, 0.06]}>
            <mesh castShadow receiveShadow geometry={nodes.mesh_289_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_290_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_291_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_292_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_293_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_294_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_295_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_296_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_297_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_298_instance_1.geometry} material={materials.material_52} />
            <mesh castShadow receiveShadow geometry={nodes.mesh_299_instance_1.geometry} material={materials.material_52} />
            <lineSegments geometry={nodes.mesh_300_instance_1.geometry} material={materials.edge_color153153153255} />
          </group>
        </group>
      </group>
    </group>
  );
}

export function CornerBR(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  return (
    <group {...props}>
        <mesh castShadow receiveShadow geometry={nodes.group_20.geometry} material={materials.material_5} position={[124.35, 102.28, 96.4]} rotation={[-0.01, 0, Math.PI]} />
    </group>
  )
}

export function CornerBL(props) {
  const { nodes, materials } = useGLTF('models/urban.glb')
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.group_21.geometry} material={materials.material_5} position={[-0.04, 102.28, 96.34]} rotation={[0, 0, Math.PI]} scale={[-1, 1, 1]} />
    </group>
  )
}

export function Corners(props) {
  return (
    <group>
      <CornerFR position={[props.dx, props.dy, props.dz]}/>
      <CornerFL position={[0, props.dy, props.dz]} />
      <CornerBL position={[0, props.dy, props.dz]} />
      <CornerBR position={[props.dx, props.dy, props.dz]} />      
    </group>
  );
}

export function Sticks(props) {

  const {dx, dy, dz} = props;
  const list = [];
  const frame_cnt = parseInt(props.length / props.frame_int_size);
  const frame_size = props.length / frame_cnt - 0.2;

  const px = -30.6;
  const py = 0;
  const pz = 0;

  for (var i = 1 ; i < frame_cnt ; i++ ) {
    list.push(
      <Stick
        position = {[px + i * frame_size, py, pz]}
      />
    )
  }


  return (
    <group position={[dx, dy, dz]}>
      {list}
    </group>
  )  
}

export function Urban(props) {
  // const { nodes, materials } = useGLTF('models/urban.glb')
  const modelID = props.modelID;
  const snap = useSnapshot(state);


  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03} position={[-(snap[modelID].length.width-lengths[modelID].int_width)/2 * 0.001, 0, 0]}>
        <Frame 
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
          length = {lengths[modelID].unit * snap[modelID].length.width}
          frame_int_size = {lengths[modelID].frame_width}
        />
        <BackSide
          sx={snap[modelID].length.width / lengths[modelID].int_width}
          dx = {0}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
        />
        <FrontSide 
          sx={snap[modelID].length.width / lengths[modelID].int_width}
          dx = {0}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
        />
        <Bars 
          dx = {lengths[modelID].unit * (snap[modelID].length.width - lengths[modelID].int_width)}
          sz = {snap[modelID].length.height_1 / lengths[modelID].int_height_1}
        />
        <Bottoms 
          dx = {lengths[modelID].unit * (snap[modelID].length.width - lengths[modelID].int_width)}
          dy = {0}
          dz = {0}
        />
        <LeftSide 
          dx = {0}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
          sy = {snap[modelID].length.depth / lengths[modelID].int_depth}
        />
        <RightSide 
          dx = {lengths[modelID].unit * (snap[modelID].length.width - lengths[modelID].int_width)}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
        />
        <Sticks
          dx = {0}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
          length = {lengths[modelID].unit * snap[modelID].length.width}
          frame_int_size = {lengths[modelID].frame_width}
        />
        <Corners 
          dx = {lengths[modelID].unit * (snap[modelID].length.width - lengths[modelID].int_width)}
          dy = {0}
          dz = {lengths[modelID].unit * (snap[modelID].length.height_1 - lengths[modelID].int_height_1)}
        />

      </group>
    </group>
  )
}

useGLTF.preload('models/urban.glb')
